"""Which platforms one profile reaches, grouped by how each one takes a candidate.

Drives the diagram on the advisory page (``asesoria/index.html``). Every group is read from
the code — ``AtsKind``, the adapter registry, the account-need table and the job sources — so
the page cannot name a platform JobBot does not know, nor miss one it learned. ``make site``
rewrites the figure, the cargo lifecycle and the Luma comparison table between their markers;
a stale page fails the suite.
"""

from __future__ import annotations

import argparse
import itertools
import sys
import textwrap
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from html import escape
from pathlib import Path
from typing import get_args

from jobbot.adapters.ats.registry import supported_kinds
from jobbot.adapters.base import ApplyMethod
from jobbot.advisory.compare import COMPARE_END, COMPARE_START, render_comparison
from jobbot.advisory.lifecycle import LIFECYCLE_END, LIFECYCLE_START, render_lifecycle
from jobbot.companies.signup import AccountNeed, account_need
from jobbot.jobs.sources import JobSourceName
from jobbot.portals.detect import JOB_BOARD_KINDS, AtsKind, html_marker_kinds
from jobbot.workspace import repo_root

PAGE_RELPATH = Path("asesoria/index.html")
MAP_START = "<!-- platform-map:start (generated by `make site`; do not edit by hand) -->"
MAP_END = "<!-- platform-map:end -->"

# Brand spelling only; a kind missing here still shows up, under its own value.
_LABELS: dict[str, str] = {
    "greenhouse": "Greenhouse",
    "lever": "Lever",
    "workday": "Workday",
    "ashby": "Ashby",
    "getonboard": "Get on Board",
    "smartrecruiters": "SmartRecruiters",
    "bamboohr": "BambooHR",
    "successfactors": "SuccessFactors",
    "oracle": "Oracle Taleo",
    "teamtailor": "Teamtailor",
    "workable": "Workable",
    "recruitee": "Recruitee",
    "breezy": "Breezy HR",
    "manatal": "Manatal",
    "torre": "Torre",
    "jobtome": "Jobtome",
    "remoshift": "Remoshift",
    "remoteyeah": "RemoteYeah",
    "jobgether": "Jobgether",
    "vacantes": "Vacantes.com",
    "empleos_publicos": "Empleos Públicos",
    "indeed": "Indeed",
    "linkedin": "LinkedIn",
    "email": "Correo al reclutador",
}


@dataclass(frozen=True)
class Platform:
    """One destination on the diagram; ``kind`` is None for a generic one."""

    label: str
    assisted: bool
    kind: AtsKind | None = None


@dataclass(frozen=True)
class Flavour:
    """Platforms that take a candidate the same way."""

    key: str
    title: str
    note: str
    platforms: tuple[Platform, ...]


def platform_label(kind: AtsKind) -> str:
    return _LABELS.get(kind.value, kind.value.capitalize())


def source_kinds() -> tuple[AtsKind, ...]:
    """Platform behind each discovery source (``linkedin_post`` → LinkedIn), in order."""
    kinds: list[AtsKind] = []
    for name in get_args(JobSourceName):
        raw = str(name)
        for candidate in (raw, raw.split("_", 1)[0]):
            try:
                kinds.append(AtsKind(candidate))
                break
            except ValueError:
                continue
    return tuple(dict.fromkeys(kinds))


def _assisted_kinds() -> frozenset[AtsKind]:
    """Registry adapters, plus apply routes the adapters own themselves (email)."""
    routes = {method.value for method in ApplyMethod} - {ApplyMethod.UNKNOWN.value}
    return supported_kinds() | {kind for kind in AtsKind if kind.value in routes}


def _spoken_list(labels: Sequence[str]) -> str:
    if len(labels) < 2:
        return "".join(labels)
    return f"{', '.join(labels[:-1])} y {labels[-1]}"


def platform_flavours() -> tuple[Flavour, ...]:
    """Every known platform in exactly one group, read from the code that serves it."""
    assisted = _assisted_kinds()

    def group(kinds: Iterable[AtsKind]) -> tuple[Platform, ...]:
        return tuple(Platform(platform_label(k), k in assisted, k) for k in kinds)

    known = [kind for kind in AtsKind if kind is not AtsKind.UNKNOWN]
    ats = [kind for kind in known if kind not in JOB_BOARD_KINDS and kind is not AtsKind.EMAIL]

    def ats_needing(need: AccountNeed) -> tuple[Platform, ...]:
        return group(kind for kind in ats if account_need(kind) is need)

    sources = source_kinds()
    boards = [*sources, *(k for k in known if k in JOB_BOARD_KINDS and k not in sources)]
    searched = _spoken_list([platform_label(kind) for kind in sources])
    markers = len(html_marker_kinds())
    return (
        Flavour(
            "ats_open",
            "ATS sin cuenta",
            "Postulas directo en el formulario de cada empresa.",
            ats_needing(AccountNeed.NOT_NEEDED),
        ),
        Flavour(
            "ats_account",
            "ATS con cuenta por empresa",
            "Cada empresa abre su propia cuenta: la contraseña la pones tú.",
            ats_needing(AccountNeed.NEEDED),
        ),
        Flavour(
            "ats_unknown",
            "Otros ATS reconocidos",
            "Si piden cuenta se confirma al entrar; nada se da por hecho.",
            ats_needing(AccountNeed.UNKNOWN),
        ),
        Flavour(
            "boards",
            "Portales permanentes y job boards",
            f"Tu perfil al día; búsqueda de ofertas en {searched}.",
            group(boards),
        ),
        Flavour(
            "own_sites",
            "Sitios propios de empresas",
            f"Se reconoce el ATS que cargan por dentro: {markers} plataformas "
            "por marcador técnico.",
            (Platform("Página de empleo propia", False),),
        ),
        Flavour(
            "email",
            "Postulación por email",
            "Borrador en Gmail con tu CV adjunto; el envío es tuyo.",
            group([AtsKind.EMAIL]),
        ),
    )


# The page names these in prose; ``AtsKind(value)`` raises if one ever leaves the code.
_FEATURED: tuple[str, ...] = (
    "workday",
    "greenhouse",
    "lever",
    "ashby",
    "smartrecruiters",
    "workable",
    "manatal",
    "getonboard",
    "indeed",
    "linkedin",
    "torre",
    "email",
)


def featured_platforms() -> tuple[AtsKind, ...]:
    """The platforms the page names by hand; fails loudly if the code drops one."""
    return tuple(AtsKind(value) for value in _FEATURED)


@dataclass(frozen=True)
class LearningStep:
    """Something JobBot learns on the platforms that comes back as a proposal."""

    title: str
    note: str
    commands: tuple[str, ...]


def feedback_loop() -> tuple[LearningStep, ...]:
    """What flows back to the profile, each step backed by a command that exists."""
    return (
        LearningStep("Ofertas leídas", "requisitos del mercado", ("jobs search", "linkedin sweep")),
        LearningStep("Preguntas de formularios", "lo que piden de verdad", ("portals form-learn",)),
        LearningStep(
            "Sugerencias del mercado",
            "el lenguaje que se repite",
            ("profile suggest-from-market",),
        ),
        LearningStep("Mejora diaria del CV", "pocas propuestas por día", ("cv advise",)),
    )


# ── SVG rendering ──────────────────────────────────────────────────────────────
# Coordinates are written as "x,y" pairs: a run of space-separated digits would read as a
# phone number to the page's contact-data checks.

_PAD = 12
_GAP = 12
_LANE_LABEL = "Lo que aprendemos vuelve a tu perfil — tú confirmas"


@dataclass(frozen=True)
class _Type:
    title: int
    note: int
    chip: int


@dataclass(frozen=True)
class _Node:
    cls: str
    title: str
    note: str
    cmd: str = ""


_PROFILE = _Node("pm-source", "Tu perfil · fuente única de verdad", "solo hechos que confirmaste")
_CV = _Node("pm-node", "CV LaTeX → PDF", "se adjunta donde lo piden")
_MAP = _Node(
    "pm-node",
    "Mapa empresa ↔ plataforma",
    "compartido y creciente; se revisa antes de activarse",
)
_ADAPTERS = _Node("pm-hub", "Adaptadores", "rellenan lo que tu perfil ya responde")
_GATE = _Node("pm-gate", "Tú confirmas", "nada entra a tu perfil sin tu confirmación")


def _wrap(text: str, width: int) -> list[str]:
    return textwrap.wrap(text, width, break_long_words=False, break_on_hyphens=False)


def _chars(width: int, size: int, *, bold: bool = False, mono: bool = False) -> int:
    ratio = 0.62 if mono else 0.6 if bold else 0.53
    return max(8, int(width / (size * ratio)))


def _text_width(text: str, size: int, *, bold: bool) -> int:
    return int(len(text) * size * (0.62 if bold else 0.56)) + 1


def _learning_nodes() -> list[_Node]:
    return [_Node("pm-learn", s.title, s.note, " · ".join(s.commands)) for s in feedback_loop()]


def _node_lines(node: _Node, width: int, kind: _Type) -> tuple[list[str], list[str], list[str]]:
    inner = width - 2 * _PAD
    titles = _wrap(node.title, _chars(inner, kind.title, bold=True))
    notes = _wrap(node.note, _chars(inner, kind.note))
    cmds = _wrap(node.cmd, _chars(inner, kind.note - 1, mono=True)) if node.cmd else []
    return titles, notes, cmds


def _node_content(node: _Node, width: int, kind: _Type) -> int:
    titles, notes, cmds = _node_lines(node, width, kind)
    return (
        len(titles) * (kind.title + 4)
        + 4
        + len(notes) * (kind.note + 5)
        + len(cmds) * (kind.note + 4)
    )


def _node_height(node: _Node, width: int, kind: _Type) -> int:
    return 2 * _PAD + _node_content(node, width, kind) + 4


def _node(node: _Node, x: int, y: int, width: int, height: int, kind: _Type) -> str:
    titles, notes, cmds = _node_lines(node, width, kind)
    cursor = y + (height - _node_content(node, width, kind)) // 2 - 2
    center = x + width // 2
    parts = [f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="10"/>']
    for title in titles:
        cursor += kind.title + 4
        parts.append(
            f'<text class="pm-title" x="{center}" y="{cursor}" font-size="{kind.title}" '
            f'font-weight="700" text-anchor="middle">{escape(title)}</text>'
        )
    cursor += 4
    for note in notes:
        cursor += kind.note + 5
        parts.append(
            f'<text class="pm-note" x="{center}" y="{cursor}" font-size="{kind.note}" '
            f'text-anchor="middle">{escape(note)}</text>'
        )
    for cmd in cmds:
        cursor += kind.note + 4
        parts.append(
            f'<text class="pm-cmd" x="{center}" y="{cursor}" font-size="{kind.note - 1}" '
            f'text-anchor="middle">{escape(cmd)}</text>'
        )
    body = "\n".join(f"    {part}" for part in parts)
    return f'  <g class="{node.cls}">\n{body}\n  </g>'


def _chip_rows(
    platforms: Sequence[Platform], inner: int, kind: _Type
) -> list[list[tuple[Platform, int]]]:
    rows: list[list[tuple[Platform, int]]] = []
    used = 0
    for platform in platforms:
        width = _text_width(platform.label, kind.chip, bold=platform.assisted) + 18
        if rows and used + 6 + width <= inner:
            rows[-1].append((platform, width))
            used += 6 + width
        else:
            rows.append([(platform, width)])
            used = width
    return rows


def _chip(x: int, y: int, width: int, height: int, platform: Platform, size: int) -> str:
    cls = "pm-chip pm-chip-assisted" if platform.assisted else "pm-chip"
    weight = ' font-weight="700"' if platform.assisted else ""
    baseline = y + height // 2 + (size * 35) // 100
    return (
        f'<g class="{cls}"><rect x="{x}" y="{y}" width="{width}" height="{height}" '
        f'rx="{height // 2}"/><text x="{x + width // 2}" y="{baseline}" font-size="{size}" '
        f'text-anchor="middle"{weight}>{escape(platform.label)}</text></g>'
    )


def _group_parts(
    x: int, y: int, width: int, flavour: Flavour, kind: _Type
) -> tuple[list[str], int]:
    """One flavour as a box of platform nodes; returns its markup lines and height."""
    inner = width - 2 * _PAD
    lines: list[str] = []
    cursor = y + _PAD
    for title in _wrap(flavour.title, _chars(inner, kind.title, bold=True)):
        cursor += kind.title + 4
        lines.append(
            f'<text class="pm-title" x="{x + _PAD}" y="{cursor}" font-size="{kind.title}" '
            f'font-weight="700">{escape(title)}</text>'
        )
    cursor += 2
    for note in _wrap(flavour.note, _chars(inner, kind.note)):
        cursor += kind.note + 5
        lines.append(
            f'<text class="pm-note" x="{x + _PAD}" y="{cursor}" font-size="{kind.note}">'
            f"{escape(note)}</text>"
        )
    cursor += 10
    chip_h = kind.chip + 12
    for row in _chip_rows(flavour.platforms, inner, kind):
        left = x + _PAD
        for platform, chip_w in row:
            lines.append(_chip(left, cursor, chip_w, chip_h, platform, kind.chip))
            left += chip_w + 6
        cursor += chip_h + 6
    height = cursor - 6 - y + _PAD
    rect = f'<rect class="pm-box" x="{x}" y="{y}" width="{width}" height="{height}" rx="10"/>'
    return [rect, *lines], height


def _group(lines: Sequence[str], edge: str) -> str:
    body = "\n".join(f"    {line}" for line in [edge.strip(), *lines])
    return f'  <g class="pm-group">\n{body}\n  </g>'


def _edge(layout: str, d: str, *, back: bool = False, arrow: bool = True) -> str:
    cls = "pm-feedback" if back else "pm-flow"
    marker = f"pm-{layout}-arrow{'-back' if back else ''}"
    end = f' marker-end="url(#{marker})"' if arrow else ""
    return f'  <path class="{cls}" d="{d}"{end}/>'


def _lane_label(x: int, y: int, size: int, lines: Sequence[str], anchor: str) -> str:
    spans = "".join(
        f'<tspan x="{x}" dy="{0 if i == 0 else size + 4}">{escape(line)}</tspan>'
        for i, line in enumerate(lines)
    )
    return (
        f'  <text class="pm-lane" x="{x}" y="{y}" font-size="{size}" font-weight="700" '
        f'text-anchor="{anchor}">{spans}</text>'
    )


def _description(flavours: Sequence[Flavour]) -> str:
    groups = " ".join(f"{f.title}: {', '.join(p.label for p in f.platforms)}." for f in flavours)
    assisted = ", ".join(p.label for f in flavours for p in f.platforms if p.assisted)
    learned = "; ".join(f"{s.title} ({s.note})" for s in feedback_loop())
    return (
        "Tu perfil, fuente única de verdad, genera tu CV LaTeX y PDF y alimenta a los "
        "adaptadores, que se guían por el mapa compartido de qué empresa usa qué plataforma. "
        f"Desde ahí llega a cada tipo de postulación. {groups} "
        f"Con relleno asistido de los campos que tu perfil ya responde: {assisted}. "
        f"{_LANE_LABEL}: {learned}. Tú confirmas: {_GATE.note}."
    )


def _svg(layout: str, width: int, height: int, body: Sequence[str], desc: str) -> str:
    head = (
        f'<svg class="pm-{layout}" viewBox="0,0,{width},{height}" role="img" '
        f'aria-labelledby="pm-{layout}-title pm-{layout}-desc">'
    )
    markers = "".join(
        f'<marker id="pm-{layout}-arrow{suffix}" viewBox="0,0,10,10" refX="9" refY="5" '
        'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
        f'<path class="pm-arrowhead{suffix}" d="M0,0 L10,5 L0,10 z"/></marker>'
        for suffix in ("", "-back")
    )
    return "\n".join(
        [
            head,
            f'  <title id="pm-{layout}-title">De tu perfil a cada plataforma de postulación, '
            "y de vuelta</title>",
            f'  <desc id="pm-{layout}-desc">{escape(desc)}</desc>',
            f"  <defs>{markers}</defs>",
            *body,
            "</svg>",
        ]
    )


def _render_wide(flavours: Sequence[Flavour]) -> str:
    width, kind = 1140, _Type(title=17, note=14, chip=14)
    fb_x, fb_w = 16, 240
    c_x, c_w = 290, 210
    a_x, a_w = 530, 140
    g_x, g_w = 710, 414

    groups: list[tuple[list[str], int, int]] = []
    cursor = 16
    for flavour in flavours:
        lines, height = _group_parts(g_x, cursor, g_w, flavour, kind)
        groups.append((lines, cursor, height))
        cursor += height + _GAP
    g_bottom = cursor - _GAP
    mid = (16 + g_bottom) // 2

    profile_h = _node_height(_PROFILE, c_w, kind) + 8
    profile_y = mid - profile_h // 2
    map_h = _node_height(_MAP, c_w, kind)
    map_y = max(16, profile_y - 60 - map_h)
    cv_h = _node_height(_CV, c_w, kind)
    cv_y = profile_y + profile_h + 60
    gate_h = _node_height(_GATE, fb_w, kind)
    gate_y = mid - gate_h // 2

    learning: list[tuple[_Node, int, int]] = []
    y = gate_y + gate_h + 28
    for node in reversed(_learning_nodes()):
        height = _node_height(node, fb_w, kind)
        learning.append((node, y, height))
        y += height + 28
    fb_bottom = y - 28
    lane_y = max(g_bottom, fb_bottom, cv_y + cv_h) + 40
    c_right, a_right = c_x + c_w, a_x + a_w
    fb_center, c_center = fb_x + fb_w // 2, c_x + c_w // 2
    map_mid, cv_mid = map_y + map_h // 2, cv_y + cv_h // 2
    g_center = g_x + g_w // 2

    body = [
        _edge("wide", f"M{c_right},{mid} L{a_x - 2},{mid}"),
        _edge("wide", f"M{c_center},{profile_y + profile_h} L{c_center},{cv_y - 2}"),
        _edge("wide", f"M{c_right},{cv_mid} L{a_x - 2},{cv_mid}"),
        _edge("wide", f"M{c_right},{map_mid} L{a_x - 2},{map_mid}"),
        _edge(
            "wide",
            f"M{g_center},{g_bottom} L{g_center},{lane_y} L{fb_center},{lane_y} "
            f"L{fb_center},{fb_bottom + 2}",
            back=True,
        ),
        _edge("wide", f"M{fb_x + fb_w},{mid} L{c_x - 2},{mid}", back=True),
    ]
    stack = [(gate_y, gate_h), *((top, height) for _, top, height in learning)]
    for (upper, upper_h), (lower, _) in itertools.pairwise(stack):
        body.append(
            _edge("wide", f"M{fb_center},{lower} L{fb_center},{upper + upper_h + 2}", back=True)
        )
    label_x = (fb_x + fb_w + g_center) // 2
    body.append(_lane_label(label_x, lane_y - 10, kind.note + 2, [_LANE_LABEL], "middle"))
    for lines, top, height in groups:
        target = top + height // 2
        body.append(_group(lines, _edge("wide", f"M{a_right},{target} L{g_x - 2},{target}")))
    body += [
        _node(_ADAPTERS, a_x, 16, a_w, g_bottom - 16, kind),
        _node(_PROFILE, c_x, profile_y, c_w, profile_h, kind),
        _node(_CV, c_x, cv_y, c_w, cv_h, kind),
        _node(_MAP, c_x, map_y, c_w, map_h, kind),
        _node(_GATE, fb_x, gate_y, fb_w, gate_h, kind),
        *(_node(node, fb_x, top, fb_w, height, kind) for node, top, height in learning),
    ]
    return _svg("wide", width, lane_y + 20, body, _description(flavours))


def _render_narrow(flavours: Sequence[Flavour]) -> str:
    width, kind = 360, _Type(title=17, note=14, chip=15)
    left, full = 12, 320
    lane_x = 346
    half = (full - 16) // 2
    right = left + half + 16
    profile_h = _node_height(_PROFILE, full, kind) + 8
    row_y = 16 + profile_h + 36
    row_h = max(_node_height(_CV, half, kind), _node_height(_MAP, half, kind))
    hub_y = row_y + row_h + 36
    hub_h = _node_height(_ADAPTERS, full, kind)
    spine, groups_x = 22, 38
    groups_w = left + full - groups_x

    groups: list[str] = []
    cursor = hub_y + hub_h + 24
    last_mid = cursor
    for flavour in flavours:
        lines, height = _group_parts(groups_x, cursor, groups_w, flavour, kind)
        last_mid = cursor + height // 2
        branch = _edge("narrow", f"M{spine},{last_mid} L{groups_x - 2},{last_mid}")
        groups.append(_group(lines, branch))
        cursor += height + _GAP
    g_bottom = cursor - _GAP

    label_lines = _wrap(_LANE_LABEL, 22)
    label_y = g_bottom + 30
    first_y = label_y + (len(label_lines) - 1) * (kind.note + 6) + 26
    drop_x = groups_x + groups_w - 36
    feedback = [
        _lane_label(groups_x, label_y, kind.note + 2, label_lines, "start"),
        _edge("narrow", f"M{drop_x},{g_bottom} L{drop_x},{first_y - 2}", back=True),
    ]
    nodes: list[str] = []
    y = first_y
    center = groups_x + groups_w // 2
    chain = [*_learning_nodes(), _GATE]
    for index, node in enumerate(chain):
        height = _node_height(node, groups_w, kind)
        nodes.append(_node(node, groups_x, y, groups_w, height, kind))
        y += height
        if index < len(chain) - 1:
            feedback.append(_edge("narrow", f"M{center},{y} L{center},{y + 22}", back=True))
            y += 24
    gate_mid = y - _node_height(_GATE, groups_w, kind) // 2
    profile_mid = 16 + profile_h // 2
    feedback.append(
        _edge(
            "narrow",
            f"M{groups_x + groups_w},{gate_mid} L{lane_x},{gate_mid} L{lane_x},{profile_mid} "
            f"L{left + full + 2},{profile_mid}",
            back=True,
        )
    )
    cv_center, map_center, mid_x = left + half // 2, right + half // 2, left + full // 2
    profile_bottom, row_bottom = 16 + profile_h, row_y + row_h
    body = [
        _edge("narrow", f"M{cv_center},{profile_bottom} L{cv_center},{row_y - 2}"),
        _edge("narrow", f"M{mid_x},{profile_bottom} L{mid_x},{hub_y - 2}"),
        _edge("narrow", f"M{cv_center},{row_bottom} L{cv_center},{hub_y - 2}"),
        _edge("narrow", f"M{map_center},{row_bottom} L{map_center},{hub_y - 2}"),
        _edge("narrow", f"M{spine},{hub_y + hub_h} L{spine},{last_mid}", arrow=False),
        *feedback,
        _node(_PROFILE, left, 16, full, profile_h, kind),
        _node(_CV, left, row_y, half, row_h, kind),
        _node(_MAP, right, row_y, half, row_h, kind),
        _node(_ADAPTERS, left, hub_y, full, hub_h, kind),
        *groups,
        *nodes,
    ]
    return _svg("narrow", width, y + 16, body, _description(flavours))


def render_figure() -> str:
    """The ``<figure>`` for the page: wide and narrow diagrams plus a computed caption."""
    featured_platforms()
    flavours = platform_flavours()
    recognised = sum(len([p for p in f.platforms if p.kind is not None]) for f in flavours)
    assisted = sum(p.assisted for f in flavours for p in f.platforms)
    caption = (
        "Las flechas azules llevan tu perfil a cada plataforma; las naranjas traen de vuelta "
        "lo que JobBot aprende, que entra a tu perfil solo si tú lo confirmas. "
        "<strong>Con borde marcado:</strong> JobBot rellena los campos que tu perfil ya "
        "responde; tú revisas y envías. El resto: se reconoce la plataforma y se arma tu "
        f"hoja de datos. Hoy JobBot reconoce {recognised} plataformas y vías de postulación; "
        f"en {assisted} rellena por ti. Este diagrama se genera desde el código de JobBot, "
        "así que crece junto con el mapa."
    )
    return "\n".join(
        [
            '<figure class="platform-map">',
            _render_wide(flavours),
            _render_narrow(flavours),
            f"<figcaption>{caption}</figcaption>",
            "</figure>",
        ]
    )


def inject_between(page: str, start_mark: str, end_mark: str, body: str, *, missing: str) -> str:
    """Swap the block between two HTML comment markers, keeping indentation."""
    start, end = page.find(start_mark), page.find(end_mark)
    if start < 0 or end < start:
        raise ValueError(missing)
    indent = page[page.rfind("\n", 0, start) + 1 : start]
    if indent.strip():
        indent = ""
    rendered = "\n".join(f"{indent}{line}" if line else line for line in body.splitlines())
    return f"{page[: start + len(start_mark)]}\n{rendered}\n{indent}{page[end:]}"


def inject_figure(page: str, figure: str) -> str:
    """Replace what sits between the page markers, keeping the markers' indentation."""
    return inject_between(
        page,
        MAP_START,
        MAP_END,
        figure,
        missing="page has no platform-map markers",
    )


def inject_comparison(page: str, table: str) -> str:
    """Replace the Luma comparison table between its markers."""
    return inject_between(
        page,
        COMPARE_START,
        COMPARE_END,
        table,
        missing="page has no comparison markers",
    )


def inject_lifecycle(page: str, figure: str) -> str:
    """Replace the cargo-lifecycle figure between its markers."""
    return inject_between(
        page,
        LIFECYCLE_START,
        LIFECYCLE_END,
        figure,
        missing="page has no cargo-lifecycle markers",
    )


def write_page(root: Path) -> Path:
    target = root / PAGE_RELPATH
    page = target.read_text(encoding="utf-8")
    page = inject_figure(page, render_figure())
    page = inject_lifecycle(page, render_lifecycle())
    page = inject_comparison(page, render_comparison())
    target.write_text(page, encoding="utf-8")
    return target


def main(argv: Sequence[str] | None = None, *, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m jobbot.portals.platform_map",
        description="Render the advisory page's platform diagram from the code.",
    )
    parser.add_argument("--write", action="store_true", help=f"rewrite {PAGE_RELPATH}")
    args = parser.parse_args(argv)
    if args.write:
        target = write_page(root or repo_root())
        sys.stdout.write(f"Wrote {target}\n")
    else:
        sys.stdout.write(render_figure() + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
