"""Pieces shared by the CV importers: result type, sections, dates, ids."""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

_MONTHS: dict[str, int] = {
    "ene": 1,
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "abr": 4,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "ago": 8,
    "aug": 8,
    "sep": 9,
    "sept": 9,
    "oct": 10,
    "nov": 11,
    "dic": 12,
    "dec": 12,
}

SKILL_GROUP_MAP: dict[str, str] = {
    # English synonyms may collapse; Spanish (and unknown) labels keep their own slug
    # so a Spanish CV still renders Spanish group names.
    "languages": "programming",
    "programming": "programming",
    "machine learning": "machine_learning",
    "cloud": "cloud",
    "methods": "statistics",
    "statistics": "statistics",
    "engineering": "engineering",
    "mlops": "engineering",
}

SECTION_KINDS: dict[str, tuple[str, ...]] = {
    "summary": ("resumen", "summary", "perfil", "about", "profile"),
    "experience": (
        "experiencia profesional",
        "experiencia academica",
        "experiencia académica",
        "experiencia docente",
        "experiencia",
        "experience",
        "empleo",
        "academic experience",
        "teaching",
        "docente",
    ),
    "education": (
        "formacion academica",
        "formación académica",
        "formacion",
        "formación",
        "educacion",
        "educación",
        "education",
        "conocimiento complementario",
        "conocimientos complementarios",
        "cursos",
        "certificaciones",
        "capacitacion",
        "capacitación",
    ),
    "skills": (
        "habilidades",
        "skills",
        "competencias",
        "técnicas",
        "tecnicas",
        "conocimientos en sistemas",
        "conocimiento en sistemas",
        "herramientas",
        "software",
    ),
    "publications": ("publicaciones", "publications"),
}



@dataclass
class ImportResult:
    """Result of importing a CV from any source format."""

    data: dict[str, Any]
    source_path: Path
    warnings: list[str] = field(default_factory=list)

    @property
    def experience_count(self) -> int:
        return len(self.data.get("experience", []))

    @property
    def achievement_count(self) -> int:
        return sum(len(e.get("achievements", [])) for e in self.data.get("experience", []))

    @property
    def skill_count(self) -> int:
        skills = self.data.get("skills", {})
        return sum(len(v) for v in skills.values() if isinstance(v, list))


def write_generated_profile(
    result: ImportResult,
    destination: Path,
    *,
    command: str = "profile import-latex",
) -> Path:
    """Write imported profile YAML. Never writes to profile.yaml by itself."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by jobbot {command}\n"
        f"# Source: {result.source_path}\n"
        f"# Review carefully, then promote with:\n"
        f"#   jobbot profile promote-generated\n"
        f"# or:\n"
        f"#   cp {destination} data/profile.yaml\n"
        f"#\n"
    )
    body = yaml.safe_dump(
        result.data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=88,
    )
    destination.write_text(header + body, encoding="utf-8")
    return destination


def empty_skills() -> dict[str, list[str]]:
    """No pre-seeded groups: a profile only gets the groups its CV actually has."""
    return {}


def section_match(title: str) -> tuple[str, float] | None:
    """Best matching section kind plus how much of the heading the alias covers."""
    norm = normalize_key(title)
    if not norm:
        return None
    best: tuple[int, str] | None = None
    for kind, aliases in SECTION_KINDS.items():
        for alias in aliases:
            alias_norm = normalize_key(alias)
            if alias_norm and alias_norm in norm:
                score = len(alias_norm)
                if best is None or score > best[0]:
                    best = (score, kind)
    if best is None:
        return None
    return best[1], best[0] / len(norm)


def section_kind(title: str) -> str | None:
    """Map a heading to summary/experience/education/skills/publications."""
    match = section_match(title)
    return match[0] if match else None


def map_skill_group(label: str) -> str:
    """Map a CV's own section label to a profile group, keeping it when unknown.

    Falling back to a fixed group files a nurse's clinical skills under
    'engineering'; the label the CV used is better evidence than our guess.
    Short English synonyms (languages → programming) still collapse; Spanish
    labels keep their own slug so the rendered CV stays in the CV's language.
    """
    norm = normalize_key(label)
    if norm in SKILL_GROUP_MAP:
        return SKILL_GROUP_MAP[norm]
    # Substring match only for longer keys, so "cloud" does not swallow
    # "big data & cloud".
    for key, group in sorted(SKILL_GROUP_MAP.items(), key=lambda item: -len(item[0])):
        if len(key) < 8:
            continue
        if key in norm or norm in key:
            return group
    slug = re.sub(r"[^a-z0-9]+", "_", norm).strip("_")
    return slug or "other"


def parse_date_range(text: str) -> dict[str, Any]:
    """Split 'Sep 2020 -- Present' or '10/2024 – 11/2025' into start/end/current."""
    cleaned = re.sub(r"\([^)]*\)", "", text).strip()
    cleaned = cleaned.replace("—", "--").replace("–", "--").replace("−", "--")
    parts = [p.strip() for p in re.split(r"\s*--\s*", cleaned, maxsplit=1)]
    start_raw = parts[0] if parts else ""
    end_raw = parts[1] if len(parts) > 1 else ""

    start = parse_one_date(start_raw, end=False)
    current = False
    end: str | None = None

    if len(parts) == 1:
        # Single date token without range separator.
        current = False
        end = None
    elif end_raw == "" or is_present(end_raw):
        current = True
        end = None
    else:
        end = parse_one_date(end_raw, end=True)

    return {"start_date": start, "end_date": end, "current": current}


def is_present(text: str) -> bool:
    return bool(
        re.search(r"presente|present|actualidad|actual|hoy|current", text, re.IGNORECASE)
    )


def parse_one_date(raw: str, *, end: bool) -> str | None:
    """Return YYYY-MM for 'Sep 2020', '09/2020' or '2020'; None when unreadable."""
    text = raw.strip()
    if not text:
        return None

    numeric = re.search(r"\b(\d{1,2})\s*/\s*((?:19|20)\d{2})\b", text)
    if numeric:
        month = int(numeric.group(1))
        if 1 <= month <= 12:
            return f"{int(numeric.group(2)):04d}-{month:02d}"

    month_match = re.search(
        r"(?i)\b(ene|jan|feb|mar|abr|apr|may|jun|jul|ago|aug|sep|sept|oct|nov|dic|dec)"
        r"[a-z.]*\s+((?:19|20)\d{2})\b",
        text,
    )
    if month_match:
        mon = _MONTHS[month_key(month_match.group(1))]
        year = int(month_match.group(2))
        return f"{year:04d}-{mon:02d}"

    year_only = re.fullmatch(r"((?:19|20)\d{2})", text.strip())
    if year_only:
        year = int(year_only.group(1))
        return f"{year:04d}-{'12' if end else '01'}"

    year_any = re.search(r"((?:19|20)\d{2})", text)
    if year_any:
        year = int(year_any.group(1))
        return f"{year:04d}-{'12' if end else '01'}"
    return None


def month_key(token: str) -> str:
    t = token.lower().rstrip(".")
    for key in sorted(_MONTHS, key=len, reverse=True):
        if t.startswith(key):
            return key
    return t[:3]


def normalize_key(text: str) -> str:
    nfkd = unicodedata.normalize("NFKD", text)
    ascii_text = "".join(c for c in nfkd if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", " ", ascii_text.lower()).strip()


def slugify(text: str) -> str:
    norm = normalize_key(text)
    slug = re.sub(r"[^a-z0-9]+", "-", norm).strip("-")
    return slug[:60]


def unique_id(base: str, seen: set[str]) -> str:
    candidate = base or "item"
    if candidate not in seen:
        seen.add(candidate)
        return candidate
    idx = 2
    while f"{candidate}-{idx}" in seen:
        idx += 1
    value = f"{candidate}-{idx}"
    seen.add(value)
    return value
