"""Advisory-page comparison: Luma workshop vs this HITL service.

The three mini-agents the class sells are already JobBot's cargo loop.
The table is generated so the JobBot column cannot drift from real commands.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import escape

# Public event page; no tracking query. Cited in issue #168.
LUMA_EVENT_URL = "https://luma.com/o156agl9"
LUMA_EVENT_TITLE = "Pon la IA a buscar trabajo por ti"

COMPARE_START = "<!-- luma-compare:start (generated by `make site`; do not edit by hand) -->"
COMPARE_END = "<!-- luma-compare:end -->"


@dataclass(frozen=True)
class CompareRow:
    """One contrast. ``commands`` back the JobBot side; they are not shown on the page."""

    workshop: str
    ours: str
    commands: tuple[str, ...] = ()


def luma_comparison_rows() -> tuple[CompareRow, ...]:
    """Claims taken from the Luma blurb, mapped to this advisory service (#168)."""
    return (
        CompareRow(
            workshop="Un miniagente afina tu CV, aunque lleve meses sin actualizarse.",
            ours=(
                "Importo tu CV y propongo cómo presentarlo. Tú confirmas cada dato. "
                "No invento experiencia."
            ),
            commands=("profile import-pdf", "cv advise"),
        ),
        CompareRow(
            workshop="Otro rastrea vacantes que sí encajan contigo.",
            ours="Busco y filtro ofertas contra tu perfil, en tu máquina.",
            commands=("jobs search", "linkedin sweep", "jobs match"),
        ),
        CompareRow(
            workshop=(
                "Otro se ocupa de las postulaciones para que dejes de copiar y pegar tus datos."
            ),
            ours="Dejo el formulario listo con lo que tu perfil ya responde. Tú envías.",
            commands=("application apply",),
        ),
        CompareRow(
            workshop="La IA busca trabajo por ti.",
            ours="Tú decides. Tú envías. JobBot queda al lado.",
        ),
        CompareRow(
            workshop="Enviar o conectar tus cuentas en el taller.",
            ours="Cuentas propias. Sin CAPTCHA, sin 2FA, sin envío automático.",
        ),
    )


def render_comparison() -> str:
    """Accessible HTML table for ``asesoria/index.html``. No scripts, no tracking."""
    href = escape(LUMA_EVENT_URL, quote=True)
    title = escape(LUMA_EVENT_TITLE)
    caption = (
        f'Taller <a href="{href}" rel="noopener noreferrer">{title}</a> '
        "(Arcon Labs, en Luma). El equipo de tres ya es esta asesoría; "
        "el envío sigue siendo tuyo."
    )
    rows = "\n".join(
        f'      <tr><th scope="row">{escape(row.workshop)}</th>'
        f"<td>{escape(row.ours)}</td></tr>"
        for row in luma_comparison_rows()
    )
    return "\n".join(
        [
            '<div class="compare-wrap">',
            '  <table class="compare">',
            f"    <caption>{caption}</caption>",
            "    <thead>",
            '      <tr><th scope="col">El taller</th><th scope="col">Acá</th></tr>',
            "    </thead>",
            "    <tbody>",
            rows,
            "    </tbody>",
            "  </table>",
            "</div>",
        ]
    )


def comparison_commands() -> tuple[str, ...]:
    """CLI paths that must exist for the JobBot column to stay honest."""
    return tuple(command for row in luma_comparison_rows() for command in row.commands)
