"""Advisory-page cargo lifecycle: every CLI command in one of two loops.

Standing presence and apply-to-a-vacancy share ``profile.yaml``. Prefix rules
place each ``collect_commands`` path in a stage; a command with no prefix fails
the suite instead of vanishing. ``make site`` injects the figure between the
page markers.
"""

from __future__ import annotations

import textwrap
from collections.abc import Sequence
from dataclasses import dataclass
from html import escape

LIFECYCLE_START = "<!-- cargo-lifecycle:start (generated by `make site`; do not edit by hand) -->"
LIFECYCLE_END = "<!-- cargo-lifecycle:end -->"

_PAD = 12
_GAP = 14
_CAPTION_PREFIX = "jobbot"


@dataclass(frozen=True)
class Stage:
    """One band of the search loop. ``prefixes`` claim CLI paths; longest wins."""

    key: str
    title: str
    note: str
    prefixes: tuple[str, ...]
    commands: tuple[str, ...] = ()


def lifecycle_blueprint() -> tuple[Stage, ...]:
    """Titles and prefixes, without resolving the live CLI yet."""
    return (
        Stage(
            "arrive",
            "Llegar · tu CV al perfil",
            "Importas hechos que ya tienes. Nada se inventa.",
            (
                "init",
                "profile import-latex",
                "profile import-pdf",
                "profile promote-generated",
                "profile validate",
                "profile show",
            ),
        ),
        Stage(
            "profile",
            "Perfil y búsquedas",
            "Queries y lenguaje del mercado; tú confirmas cada dato.",
            ("profile",),
        ),
        Stage(
            "presence",
            "Presencia tibia",
            "CV y perfiles al día en portales permanentes y empresas activas.",
            (
                "cv",
                "getonboard",
                "indeed",
                "linkedin",
                "status",
                "companies signup",
                "companies recon",
            ),
        ),
        Stage(
            "find",
            "Encontrar avisos",
            "Boards, posts de reclutadores y un enlace duro que ya tienes.",
            (
                "jobs search",
                "jobs add",
                "jobs queries",
                "get",
                "capture",
                "linkedin sweep",
                "torre",
                "getonboard search",
                "empleospublicos",
            ),
        ),
        Stage(
            "choose",
            "Elegir",
            "El aviso contra tu perfil. Tú decides a cuál entrar.",
            (
                "jobs match",
                "jobs shortlist",
                "jobs show",
                "jobs note",
                "jobs backfill-dates",
                "jobs",
            ),
        ),
        Stage(
            "apply",
            "Postular · tú envías",
            "Rellena lo que tu perfil ya responde. El envío es tuyo.",
            ("application", "applications"),
        ),
        Stage(
            "session",
            "Sesión y navegador",
            "Tu Chrome. Contraseña, CAPTCHA y 2FA siguen siendo tuyos.",
            ("browser",),
        ),
        Stage(
            "map",
            "Mapa colaborativo",
            "Quién contrata dónde y qué pregunta un formulario. Sin tu CV.",
            ("companies", "portals", "recruiters"),
        ),
        Stage(
            "ops",
            "Oficio · cuando se rompe",
            "Fallos locales. Un issue a GitHub se abre contigo.",
            ("ops",),
        ),
        Stage(
            "workspace",
            "Varios candidatos",
            "Cada persona en su sandbox. El perfil real no se pisa.",
            ("workspace", "advisor"),
        ),
        Stage(
            "misc",
            "La herramienta",
            "Versión y actualización. Un comando sin prefijo no se esconde.",
            ("version", "update"),
        ),
    )


def _matches_prefix(path: str, prefix: str) -> bool:
    return path == prefix or path.startswith(prefix + " ")


def classify_command(path: str, stages: Sequence[Stage] | None = None) -> str | None:
    """Stage key for ``path``, or None if no prefix claims it."""
    best_len = -1
    keys: set[str] = set()
    for stage in stages or lifecycle_blueprint():
        for prefix in stage.prefixes:
            if _matches_prefix(path, prefix) and len(prefix) >= best_len:
                if len(prefix) > best_len:
                    keys = {stage.key}
                    best_len = len(prefix)
                else:
                    keys.add(stage.key)
    if best_len < 0:
        return None
    if len(keys) != 1:
        joined = ", ".join(sorted(keys))
        raise ValueError(f"{path!r} matches more than one stage: {joined}")
    return next(iter(keys))


def assign_commands(
    paths: Sequence[str], stages: Sequence[Stage] | None = None
) -> tuple[Stage, ...]:
    """Fill each blueprint stage. Raises if any path has no prefix."""
    base = tuple(stages or lifecycle_blueprint())
    unknown = [path for path in paths if classify_command(path, base) is None]
    if unknown:
        raise ValueError("unclassified commands: " + ", ".join(unknown))
    buckets: dict[str, list[str]] = {stage.key: [] for stage in base}
    for path in paths:
        key = classify_command(path, base)
        assert key is not None
        buckets[key].append(path)
    return tuple(
        Stage(stage.key, stage.title, stage.note, stage.prefixes, tuple(buckets[stage.key]))
        for stage in base
    )


def collect_cli_paths() -> tuple[str, ...]:
    """Live Typer tree, same names the human types after ``jobbot``."""
    from jobbot.cli import app
    from jobbot.ops.capabilities import collect_commands

    return tuple(entry.path for entry in collect_commands(app))


def lifecycle_stages(paths: Sequence[str] | None = None) -> tuple[Stage, ...]:
    """Every CLI path in exactly one stage."""
    return assign_commands(tuple(paths) if paths is not None else collect_cli_paths())


def _wrap(text: str, width: int) -> list[str]:
    return textwrap.wrap(text, width, break_long_words=False, break_on_hyphens=False)


def _chars(width: int, size: int, *, bold: bool = False, mono: bool = False) -> int:
    ratio = 0.62 if mono else 0.6 if bold else 0.53
    return max(8, int(width / (size * ratio)))


def _text_width(text: str, size: int, *, bold: bool) -> int:
    return int(len(text) * size * (0.62 if bold else 0.56)) + 1


@dataclass(frozen=True)
class _Type:
    title: int
    note: int
    chip: int


def _chip_rows(labels: Sequence[str], inner: int, kind: _Type) -> list[list[tuple[str, int]]]:
    rows: list[list[tuple[str, int]]] = []
    used = 0
    for label in labels:
        width = min(inner, _text_width(label, kind.chip, bold=False) + 18)
        if rows and used + 6 + width <= inner:
            rows[-1].append((label, width))
            used += 6 + width
        else:
            rows.append([(label, width)])
            used = width
    return rows


def _chip(x: int, y: int, width: int, height: int, label: str, size: int) -> str:
    baseline = y + height // 2 + (size * 35) // 100
    return (
        f'<g class="pm-chip"><rect x="{x}" y="{y}" width="{width}" height="{height}" '
        f'rx="{height // 2}"/>'
        f'<text class="pm-cmd" x="{x + width // 2}" y="{baseline}" font-size="{size}" '
        f'text-anchor="middle">{escape(label)}</text></g>'
    )


def _stage_parts(
    x: int, y: int, width: int, stage: Stage, kind: _Type, *, gate: bool
) -> tuple[list[str], int]:
    inner = width - 2 * _PAD
    lines: list[str] = []
    cursor = y + _PAD
    for title in _wrap(stage.title, _chars(inner, kind.title, bold=True)):
        cursor += kind.title + 4
        lines.append(
            f'<text class="pm-title" x="{x + _PAD}" y="{cursor}" font-size="{kind.title}" '
            f'font-weight="700">{escape(title)}</text>'
        )
    cursor += 2
    for note in _wrap(stage.note, _chars(inner, kind.note)):
        cursor += kind.note + 5
        lines.append(
            f'<text class="pm-note" x="{x + _PAD}" y="{cursor}" font-size="{kind.note}">'
            f"{escape(note)}</text>"
        )
    cursor += 10
    chip_h = kind.chip + 12
    for row in _chip_rows(stage.commands, inner, kind):
        left = x + _PAD
        for label, chip_w in row:
            lines.append(_chip(left, cursor, chip_w, chip_h, label, kind.chip))
            left += chip_w + 6
        cursor += chip_h + 6
    height = cursor - 6 - y + _PAD
    box_cls = "pm-box pm-gate-box" if gate else "pm-box"
    rect = f'<rect class="{box_cls}" x="{x}" y="{y}" width="{width}" height="{height}" rx="10"/>'
    return [rect, *lines], height


def _edge(layout: str, d: str, *, back: bool = False) -> str:
    cls = "pm-feedback" if back else "pm-flow"
    marker = f"lc-{layout}-arrow{'-back' if back else ''}"
    return f'  <path class="{cls}" d="{d}" marker-end="url(#{marker})"/>'


def _description(stages: Sequence[Stage]) -> str:
    groups = " ".join(
        f"{stage.title}: {', '.join(stage.commands)}." for stage in stages if stage.commands
    )
    return (
        "Dos vueltas sobre una sola fuente de verdad, tu perfil. "
        "Presencia tibia en portales permanentes y empresas activas; "
        "después encontrar avisos, elegir y postular. "
        f"Tú confirmas. Tú envías. Comandos de {_CAPTION_PREFIX}: {groups}"
    )


def _svg(layout: str, width: int, height: int, body: Sequence[str], desc: str) -> str:
    head = (
        f'<svg class="lc-{layout}" viewBox="0,0,{width},{height}" role="img" '
        f'aria-labelledby="lc-{layout}-title lc-{layout}-desc">'
    )
    markers = "".join(
        f'<marker id="lc-{layout}-arrow{suffix}" viewBox="0,0,10,10" refX="9" refY="5" '
        'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
        f'<path class="pm-arrowhead{suffix}" d="M0,0 L10,5 L0,10 z"/></marker>'
        for suffix in ("", "-back")
    )
    return "\n".join(
        [
            head,
            f'  <title id="lc-{layout}-title">El ciclo de una búsqueda de trabajo, '
            "con los comandos de la CLI</title>",
            f'  <desc id="lc-{layout}-desc">{escape(desc)}</desc>',
            f"  <defs>{markers}</defs>",
            *body,
            "</svg>",
        ]
    )


def _header(x: int, y: int, width: int, kind: _Type) -> tuple[list[str], int]:
    title = "Tu perfil · una fuente de verdad"
    note = "Las dos vueltas parten de aquí. JobBot propone; tú confirmas."
    inner = width - 2 * _PAD
    cursor = y + _PAD
    lines: list[str] = []
    for line in _wrap(title, _chars(inner, kind.title, bold=True)):
        cursor += kind.title + 4
        lines.append(
            f'<text class="pm-title" x="{x + width // 2}" y="{cursor}" font-size="{kind.title}" '
            f'font-weight="700" text-anchor="middle">{escape(line)}</text>'
        )
    for line in _wrap(note, _chars(inner, kind.note)):
        cursor += kind.note + 5
        lines.append(
            f'<text class="pm-note" x="{x + width // 2}" y="{cursor}" font-size="{kind.note}" '
            f'text-anchor="middle">{escape(line)}</text>'
        )
    height = cursor - y + _PAD
    rect = f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="10"/>'
    return (
        ['  <g class="pm-source">', f"    {rect}", *[f"    {item}" for item in lines], "  </g>"],
        height,
    )


def _place_grid(
    layout: str,
    stages: Sequence[Stage],
    *,
    origin_x: int,
    origin_y: int,
    col_w: int,
    n_cols: int,
    kind: _Type,
) -> tuple[list[str], int]:
    rows = [list(stages[i : i + n_cols]) for i in range(0, len(stages), n_cols)]
    groups: list[str] = []
    boxes: list[tuple[int, int, int, int]] = []
    y = origin_y
    for row in rows:
        heights = [
            _stage_parts(0, 0, col_w, stage, kind, gate=stage.key == "apply")[1] for stage in row
        ]
        row_h = max(heights)
        for index, stage in enumerate(row):
            x = origin_x + index * (col_w + _GAP)
            parts, height = _stage_parts(x, y, col_w, stage, kind, gate=stage.key == "apply")
            cls = "lc-stage lc-gate" if stage.key == "apply" else "lc-stage"
            body = "\n".join(f"    {part}" for part in parts)
            groups.append(f'  <g class="{cls}">\n{body}\n  </g>')
            boxes.append((x, y, col_w, height))
        y += row_h + 36

    edges: list[str] = []
    for i, (x, top, width, height) in enumerate(boxes[:-1]):
        nxt = boxes[i + 1]
        if top == nxt[1]:
            y1 = top + height // 2
            edges.append(_edge(layout, f"M{x + width},{y1} L{nxt[0] - 2},{y1}"))
            continue
        x1 = x + width // 2
        y1 = top + height
        x2 = nxt[0] + nxt[2] // 2
        y2 = nxt[1]
        mid_y = y1 + (y2 - y1) // 2
        edges.append(_edge(layout, f"M{x1},{y1} L{x1},{mid_y} L{x2},{mid_y} L{x2},{y2 - 2}"))
    return [*edges, *groups], y - 36


def _render_wide(stages: Sequence[Stage]) -> str:
    width, kind = 1140, _Type(title=16, note=13, chip=12)
    left, full = 16, 1108
    header, header_h = _header(left, 16, full, kind)
    col_w = (full - 2 * _GAP) // 3
    grid, bottom = _place_grid(
        "wide",
        stages,
        origin_x=left,
        origin_y=16 + header_h + 28,
        col_w=col_w,
        n_cols=3,
        kind=kind,
    )
    body = [*header, *_header_to_grid_edge("wide", left, 16, full, header_h, left, col_w), *grid]
    return _svg("wide", width, bottom + 16, body, _description(stages))


def _header_to_grid_edge(
    layout: str, hx: int, hy: int, hw: int, hh: int, gx: int, col_w: int
) -> list[str]:
    x1 = hx + hw // 2
    y1 = hy + hh
    x2 = gx + col_w // 2
    y2 = hy + hh + 28
    return [_edge(layout, f"M{x1},{y1} L{x2},{y2 - 2}", back=True)]


def _render_narrow(stages: Sequence[Stage]) -> str:
    width, kind = 360, _Type(title=16, note=13, chip=12)
    left, full = 12, 336
    header, header_h = _header(left, 12, full, kind)
    grid, bottom = _place_grid(
        "narrow",
        stages,
        origin_x=left,
        origin_y=12 + header_h + 24,
        col_w=full,
        n_cols=1,
        kind=kind,
    )
    body = [
        *header,
        *_header_to_grid_edge("narrow", left, 12, full, header_h, left, full),
        *grid,
    ]
    return _svg("narrow", width, bottom + 12, body, _description(stages))


def render_lifecycle(paths: Sequence[str] | None = None) -> str:
    """The ``<figure>`` for the advisory page: wide and narrow, plus caption."""
    stages = lifecycle_stages(paths)
    n = sum(len(stage.commands) for stage in stages)
    caption = (
        f"Cada chip es un subcomando de {_CAPTION_PREFIX} ({n} en total). "
        "El mapa de arriba son las plataformas; este es el ciclo: presencia tibia "
        "y, al lado, encontrar · elegir · postular. JobBot rellena y propone; "
        "tú confirmas y tú envías."
    )
    return "\n".join(
        [
            '<figure class="lifecycle">',
            _render_wide(stages),
            _render_narrow(stages),
            f"<figcaption>{caption}</figcaption>",
            "</figure>",
        ]
    )
