"""PII pre-commit guard."""

from __future__ import annotations

from jobbot.ops.pii_guard import (
    format_report,
    is_allowed_content_path,
    is_blocked_path,
    scan_text,
)


def test_blocked_paths_cover_profile_db_and_private_latex() -> None:
    assert is_blocked_path("data/profile.yaml")
    assert is_blocked_path("data/profile.generated.yaml")
    assert is_blocked_path("data/portals.yaml")
    assert is_blocked_path("data/jobbot.sqlite")
    assert is_blocked_path("latex/cv.tex")
    assert is_blocked_path(".jobbot.toml")
    assert is_blocked_path("output/jobs/J0001/application/cv.pdf")
    assert is_blocked_path(".cursor/rules/jobbot.mdc")


def test_tracked_templates_are_not_blocked() -> None:
    assert is_blocked_path("data/profile.example.yaml") is None
    assert is_blocked_path("data/portals.example.yaml") is None
    assert is_blocked_path("latex/cv.tex.demo") is None
    assert is_blocked_path("templates/cv.tex.j2") is None
    assert is_blocked_path("src/jobbot/cli.py") is None
    assert is_blocked_path("tests/fixtures/moderncv_sample.tex") is None
    assert is_blocked_path("AGENTS.md") is None


def test_scan_text_flags_real_email_and_phone() -> None:
    findings = scan_text(
        "contact: someone@realdomain.cl phone +56 9 1234 5678",
        "docs/notes.md",
    )
    reasons = {f.reason for f in findings}
    assert "real-looking email" in reasons
    assert "phone number" in reasons


def test_scan_text_allows_placeholder_domains() -> None:
    assert scan_text("write to ana.ejemplo@example.com", "README.md") == []


def test_scan_text_flags_absolute_home_path_and_import_header() -> None:
    text = "# Generated by jobbot profile import-latex\n# Source: /Users/someone/cv/main.tex\n"
    reasons = {f.reason for f in scan_text(text, "data/notes.yaml")}
    assert "absolute home path" in reasons
    assert "import-latex header with local source path" in reasons


def test_fixtures_and_examples_are_content_allowlisted() -> None:
    assert is_allowed_content_path("tests/fixtures/linkedin_posts.txt")
    assert is_allowed_content_path("data/profile.example.yaml")
    assert is_allowed_content_path("latex/cv.tex.demo")
    assert not is_allowed_content_path("README.md")
    # Real-looking PII inside a fixture is fine (fake by construction)
    assert scan_text("seleccion@empresa.cl +56 9 1111 2222", "tests/fixtures/x.txt") == []


def test_report_mentions_paths_and_remedy() -> None:
    findings = scan_text("me@realdomain.cl", "docs/leak.md")
    report = format_report(findings)
    assert "docs/leak.md" in report
    assert "git restore --staged" in report
