"""Index of what JobBot already does, so nobody re-derives it (see AGENTS.md)."""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

import typer

INDEX_RELPATH = Path("docs/capabilities.md")

_HEADER = """# Capabilities index

Generated by `jobbot ops capabilities --write` (`make capabilities`). Do not edit by hand:
a stale index fails the test suite.

Read this before searching the tree. It exists so that reusing a function is cheaper than
writing it again — the promotion rule lives in [AGENTS.md](../AGENTS.md), section
"Design economics".
"""


@dataclass(frozen=True)
class ModuleEntry:
    """One module: where it lives, what it is for, what it exports."""

    relpath: str
    summary: str
    symbols: tuple[str, ...]

    @property
    def package(self) -> str:
        parent = str(Path(self.relpath).parent)
        return "" if parent == "." else parent


@dataclass(frozen=True)
class CommandEntry:
    """One CLI command, named as the user types it."""

    path: str
    summary: str


def _first_line(text: str | None) -> str:
    for line in (text or "").splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _is_cli_command(node: ast.AST) -> bool:
    """Typer commands are listed as commands, not as module symbols."""
    if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
        return False
    for decorator in node.decorator_list:
        call = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(call, ast.Attribute) and call.attr in {"command", "callback"}:
            return True
    return False


def collect_modules(src_root: Path) -> list[ModuleEntry]:
    """Read every module with ast; importing them would run side effects."""
    entries: list[ModuleEntry] = []
    for path in sorted(src_root.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        symbols = tuple(
            node.name
            for node in tree.body
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef)
            and not node.name.startswith("_")
            and not _is_cli_command(node)
        )
        if path.name == "__init__.py" and not symbols:
            continue
        entries.append(
            ModuleEntry(
                relpath=path.relative_to(src_root).as_posix(),
                summary=_first_line(ast.get_docstring(tree)),
                symbols=symbols,
            )
        )
    # By package first: sorting by full path interleaves a package with its subpackages.
    return sorted(entries, key=lambda entry: (entry.package, entry.relpath))


def collect_commands(app: typer.Typer) -> list[CommandEntry]:
    """Walk the Typer tree so the command names are the real ones."""
    found: list[CommandEntry] = []

    def walk(group: typer.Typer, prefix: tuple[str, ...]) -> None:
        for command in group.registered_commands:
            if command.hidden:
                continue
            callback = command.callback
            name = command.name or (callback.__name__.replace("_", "-") if callback else "?")
            summary = _first_line(command.help) or _first_line(getattr(callback, "__doc__", ""))
            found.append(CommandEntry(path=" ".join((*prefix, name)), summary=summary))
        for sub in group.registered_groups:
            inner = sub.typer_instance
            if inner is None or sub.name is None:
                continue
            walk(inner, (*prefix, sub.name))

    walk(app, ())
    return sorted(found, key=lambda entry: entry.path)


def render_index(modules: list[ModuleEntry], commands: list[CommandEntry]) -> str:
    """Markdown grouped by package, one line per module."""
    symbol_count = sum(len(entry.symbols) for entry in modules)
    lines = [
        _HEADER,
        f"{len(commands)} commands, {len(modules)} modules, {symbol_count} public symbols.",
        "",
        "## Commands",
        "",
    ]
    for command in commands:
        suffix = f" — {command.summary}" if command.summary else ""
        lines.append(f"- `jobbot {command.path}`{suffix}")
    lines.extend(["", "## Modules", ""])
    current_package: str | None = None
    for module in modules:
        if module.package != current_package:
            current_package = module.package
            lines.extend(["", f"### `{current_package or 'jobbot'}`", ""])
        parts = [f"- `{Path(module.relpath).name}`"]
        if module.summary:
            parts.append(f" — {module.summary}")
        if module.symbols:
            parts.append(" · " + ", ".join(f"`{name}`" for name in module.symbols))
        lines.append("".join(parts))
    return "\n".join(lines).replace("\n\n\n", "\n\n").rstrip() + "\n"


def build_index(repo_root: Path, app: typer.Typer) -> str:
    return render_index(collect_modules(repo_root / "src" / "jobbot"), collect_commands(app))


def write_index(repo_root: Path, app: typer.Typer) -> Path:
    target = repo_root / INDEX_RELPATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build_index(repo_root, app), encoding="utf-8")
    return target


def modules_without_summary(src_root: Path) -> list[str]:
    """A module with no docstring turns into a hole in the index."""
    return [entry.relpath for entry in collect_modules(src_root) if not entry.summary]
